export const metadata = {
  title: 'Methodology -- Nautilus Terminal',
  description: 'How NAUTILUS Terminal sources data, scores risk, generates recommendations, and evaluates answer quality.',
}

const LAST_UPDATED = 'September 2026'

export default function MethodologyPage() {
  return (
    <article className="prose-legal">
      <LegalHeader title="Methodology" date={LAST_UPDATED} />

      <Section title="1. Data Sources">
        <p>
          NAUTILUS Terminal aggregates signals from the following publicly available and third-party data
          providers. All data is fetched at runtime or on a scheduled refresh cadence and is not
          permanently stored beyond caching windows.
        </p>
        <table className="w-full text-xs mt-4 border-collapse">
          <thead>
            <tr className="border-b border-white/10">
              <th className="text-left py-2 pr-6 text-slate-300 font-semibold uppercase tracking-wide">Source</th>
              <th className="text-left py-2 pr-6 text-slate-300 font-semibold uppercase tracking-wide">Provider</th>
              <th className="text-left py-2 text-slate-300 font-semibold uppercase tracking-wide">Signal Type</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-white/5">
            <DataRow source="Commodity Prices" provider="Yahoo Finance" signal="Spot prices and historical series for crude oil, natural gas, metals, and agricultural inputs" />
            <DataRow source="Conflict &amp; Security Incidents" provider="ACLED (Armed Conflict Location &amp; Event Data Project)" signal="Geolocated conflict events, protests, and supply route disruptions" />
            <DataRow source="Seismic Events" provider="USGS Earthquake Hazards Program" signal="Real-time earthquake data used to flag infrastructure risk near production or transit hubs" />
            <DataRow source="Wildfire Detection" provider="NASA FIRMS (Fire Information for Resource Management System)" signal="Active fire perimeters and burn areas that may affect logistics corridors" />
            <DataRow source="Port Congestion &amp; Vessel Traffic" provider="MarineTraffic" signal="Vessel positions, port call data, and congestion indices for major global ports" />
            <DataRow source="Trade Flows" provider="UN Comtrade" signal="Bilateral import/export statistics by HS code, used to benchmark supplier country exposure" />
            <DataRow source="Sanctions Lists" provider="OFAC (US), UN Security Council, EU Consolidated List, BIS Entity List" signal="Restricted parties, embargoed jurisdictions, and denied entities checked against supplier names and countries" />
            <DataRow source="Foreign Exchange Rates" provider="Open Exchange Rates" signal="Daily mid-market rates for 170+ currency pairs, used to convert and normalise cost estimates" />
          </tbody>
        </table>
      </Section>

      <Section title="2. How Recommendations Work">
        <p>
          Recommendations in NAUTILUS Terminal are generated by combining structured data signals with
          large-language model reasoning. The process has two stages:
        </p>
        <h3 className="text-xs font-semibold text-slate-300 mt-4 mb-2 uppercase tracking-wide">Risk Aggregation Scoring</h3>
        <p>
          Each supplier country or trade lane receives a composite risk score derived from four signal
          categories, weighted as follows:
        </p>
        <ul>
          <li><strong className="text-slate-300">Geopolitical &amp; Security Risk (35%)</strong> &mdash; ACLED event density, active conflict proximity, and sanctions exposure</li>
          <li><strong className="text-slate-300">Natural Hazard Risk (20%)</strong> &mdash; recent USGS seismic activity and NASA FIRMS wildfire proximity to known production or transit nodes</li>
          <li><strong className="text-slate-300">Logistics &amp; Infrastructure Risk (25%)</strong> &mdash; MarineTraffic port congestion index, vessel delay rates, and chokepoint exposure</li>
          <li><strong className="text-slate-300">Economic &amp; Currency Risk (20%)</strong> &mdash; FX volatility, commodity price trend, and UN Comtrade trade balance stability</li>
        </ul>
        <p>
          Scores are normalised to a 0&ndash;100 scale per category and then aggregated using the weights
          above to produce an overall country-level risk score. A score above 65 triggers a &ldquo;High
          Risk&rdquo; flag; above 45 triggers &ldquo;Moderate Risk&rdquo;.
        </p>
        <h3 className="text-xs font-semibold text-slate-300 mt-4 mb-2 uppercase tracking-wide">Hub Scoring Algorithm</h3>
        <p>
          When the terminal recommends alternative sourcing hubs, each candidate hub is scored on:
        </p>
        <ul>
          <li>Inverse of its composite risk score (lower risk = higher hub score)</li>
          <li>Trade flow volume for the relevant HS code (proxy for supplier ecosystem depth)</li>
          <li>Freight cost estimate to the user&apos;s declared destination region</li>
          <li>Sanctions-clean status (binary gate &mdash; any OFAC/UN/EU/BIS match disqualifies the hub)</li>
        </ul>
        <p>
          The top-ranked hubs by hub score are surfaced as primary alternatives. The language model is
          then prompted with the structured scores to generate a human-readable rationale, enriched with
          any relevant live news context retrieved via semantic search.
        </p>
      </Section>

      <Section title="3. Evaluation Methodology">
        <p>
          NAUTILUS Terminal is evaluated against a benchmark of <strong className="text-slate-300">40 queries</strong> spanning
          four task categories:
        </p>
        <ul>
          <li><strong className="text-slate-300">Sourcing (10 queries)</strong> &mdash; alternative supplier identification, hub comparison, lead time estimation</li>
          <li><strong className="text-slate-300">Risk Assessment (10 queries)</strong> &mdash; country risk scoring, conflict impact, sanctions screening</li>
          <li><strong className="text-slate-300">Compliance (10 queries)</strong> &mdash; restricted party checks, import regulation lookups, documentation requirements</li>
          <li><strong className="text-slate-300">Cost &amp; FX (10 queries)</strong> &mdash; landed cost estimation, currency conversion, commodity price impact</li>
        </ul>
        <p>
          Each query has a <strong className="text-slate-300">known ground-truth answer</strong> compiled from primary sources
          (official government databases, verified trade statistics, and contemporaneous news records).
          A response is marked correct if it contains the key factual elements of the ground truth
          without material omission or contradiction. Partial credit is not awarded.
        </p>
        <p>
          Evaluation runs are conducted on each major model or data-pipeline update. Results are used
          internally to gate releases; aggregate pass rates are not currently published.
        </p>
      </Section>

      <Section title="4. Limitations">
        <p>
          Users should be aware of the following inherent limitations of the platform:
        </p>
        <ul>
          <li><strong className="text-slate-300">Data latency.</strong> Most data sources refresh daily or on event-triggered cadences. Rapidly evolving situations (active conflicts, sudden sanctions designations) may not be reflected immediately.</li>
          <li><strong className="text-slate-300">Coverage gaps.</strong> ACLED and USGS coverage is global but uneven; lower-income regions may have fewer on-the-ground reporters or monitoring stations, leading to under-reporting of incidents.</li>
          <li><strong className="text-slate-300">Model hallucination.</strong> The language model component may occasionally generate plausible-sounding but incorrect details, particularly for obscure suppliers or niche HS codes. Always verify critical facts against primary sources.</li>
          <li><strong className="text-slate-300">Not legal advice.</strong> Sanctions screening results are provided for informational triage only and do not constitute a legal compliance determination. Engage qualified legal counsel before acting on any sanctions-related output.</li>
          <li><strong className="text-slate-300">Not financial advice.</strong> Commodity price data and FX rates are indicative. Do not use them as the sole basis for hedging, contract pricing, or investment decisions.</li>
        </ul>
        <p>
          For a fuller statement of disclaimers, see our{' '}
          <a href="/legal/disclaimer" className="text-sky-400 hover:text-sky-300">Disclaimer</a> page.
        </p>
      </Section>

      <Section title="5. Contact">
        <p>
          Questions about this methodology can be directed to:
        </p>
        <p>
          NAUTILUS Intelligence<br />
          Email:{' '}
          <a href="mailto:data@nautilus-terminal.com" className="text-sky-400 hover:text-sky-300">
            data@nautilus-terminal.com
          </a>
        </p>
      </Section>
    </article>
  )
}

function LegalHeader({ title, date }) {
  return (
    <div className="mb-12 pb-8 border-b border-white/5">
      <div className="text-[10px] font-bold tracking-[0.3em] text-sky-400 uppercase mb-3">
        About the Data
      </div>
      <h1 className="text-2xl font-bold text-white mb-2">{title}</h1>
      <p className="text-xs text-slate-600">Last updated {date}</p>
    </div>
  )
}

function Section({ title, children }) {
  return (
    <section className="mb-10">
      <h2 className="text-sm font-semibold text-slate-200 mb-3 uppercase tracking-wide">
        {title}
      </h2>
      <div className="text-sm text-slate-400 leading-relaxed space-y-3 [&_ul]:list-disc [&_ul]:pl-5 [&_ul]:space-y-1.5 [&_li]:text-slate-400 [&_table]:text-slate-400">
        {children}
      </div>
    </section>
  )
}

function DataRow({ source, provider, signal }) {
  return (
    <tr>
      <td className="py-2.5 pr-6 text-slate-300 font-medium align-top">{source}</td>
      <td className="py-2.5 pr-6 text-sky-400 align-top">{provider}</td>
      <td className="py-2.5 text-slate-500 align-top">{signal}</td>
    </tr>
  )
}
