export const metadata = {
  title: 'Disclaimer -- Nautilus Terminal',
  description: 'Disclaimer regarding the accuracy and use of data provided by Nautilus Terminal.',
}

const EFFECTIVE_DATE = 'September 1, 2026'

export default function DisclaimerPage() {
  return (
    <article>
      <LegalHeader title="Disclaimer" date={EFFECTIVE_DATE} />

      <Section title="Data Accuracy">
        <p>
          Nautilus Terminal aggregates data from multiple third-party sources including news APIs,
          foreign exchange rate providers, commodity price feeds, and public trade databases. While
          we take reasonable steps to display this data accurately, we cannot guarantee its
          completeness, timeliness, or freedom from error.
        </p>
        <p>
          Data delays, API outages, and source-level inaccuracies are inherent to any real-time
          aggregation platform. Always verify critical information against primary sources before
          making procurement or business decisions.
        </p>
      </Section>

      <Section title="AI-Generated Analysis">
        <p>
          Opportunity analysis, risk assessments, strategic directives, and hub recommendations
          displayed in the terminal are generated by large language models (LLMs) operated by
          third-party AI providers. These outputs:
        </p>
        <ul>
          <li>
            May contain factual errors, hallucinations, or outdated information regardless of
            how confidently they are phrased
          </li>
          <li>
            Do not constitute professional procurement, legal, financial, or trade advice
          </li>
          <li>
            Reflect the training data and limitations of the underlying model, not independently
            verified intelligence
          </li>
          <li>
            Should be treated as a research starting point, not a final recommendation
          </li>
        </ul>
      </Section>

      <Section title="Risk Scores">
        <p>
          Port risk scores, hub stability ratings, and geopolitical risk indicators are computed
          algorithmically from third-party data and heuristic models. They are illustrative signals
          intended to direct attention -- not precise actuarial or financial risk measurements.
          Scores may lag real-world conditions during rapidly evolving events.
        </p>
      </Section>

      <Section title="No Investment or Trade Advice">
        <p>
          Nothing on this Service constitutes a recommendation to buy, sell, or hold any financial
          instrument, commodity, currency, or security. Foreign exchange and commodity data
          displayed is for informational context only. Consult a licensed financial or trade
          advisor before making investment or significant procurement commitments.
        </p>
      </Section>

      <Section title="Tariff and Trade Regulation Data">
        <p>
          Tariff information, trade flow data, and regulatory references displayed in the terminal
          are sourced from public databases and may not reflect the most recent legislative or
          regulatory changes. Trade regulations are subject to rapid change, and users should verify
          current applicable rules with qualified trade counsel or the relevant government authority
          before acting on any tariff information presented here.
        </p>
      </Section>

      <Section title="Geopolitical Information">
        <p>
          Political risk assessments and geopolitical commentary are based on publicly available
          news and analytical feeds. They represent one interpretation of a complex and rapidly
          changing environment. Nautilus Terminal does not take political positions and is not
          responsible for actions taken based on geopolitical information displayed in the Service.
        </p>
      </Section>

      <Section title="Limitation of Liability">
        <p>
          Nautilus Terminal, its operators, contributors, and data providers expressly disclaim all
          liability for any loss, damage, or negative consequence -- direct or indirect -- arising
          from reliance on information provided through this Service. This includes but is not
          limited to supply chain disruptions, procurement losses, regulatory penalties, or
          financial losses.
        </p>
      </Section>

      <Section title="Updates to This Disclaimer">
        <p>
          This disclaimer may be updated at any time. Continued use of the Service constitutes
          acceptance of the current version. The effective date above reflects when the most recent
          material revision was made.
        </p>
      </Section>
    </article>
  )
}

function LegalHeader({ title, date }) {
  return (
    <div className="mb-12 pb-8 border-b border-white/5">
      <div className="text-[10px] font-bold tracking-[0.3em] text-sky-400 uppercase mb-3">
        Legal
      </div>
      <h1 className="text-2xl font-bold text-white mb-2">{title}</h1>
      <p className="text-xs text-slate-600">Effective {date}</p>
    </div>
  )
}

function Section({ title, children }) {
  return (
    <section className="mb-10">
      <h2 className="text-sm font-semibold text-slate-200 mb-3 uppercase tracking-wide">
        {title}
      </h2>
      <div className="text-sm text-slate-400 leading-relaxed space-y-3 [&_ul]:list-disc [&_ul]:pl-5 [&_ul]:space-y-1.5 [&_li]:text-slate-400">
        {children}
      </div>
    </section>
  )
}
